/*
  # Add Sample Devoirs Conseil with Email Signature Status
  
  ## Changes
  
  Add 5 sample devoir de conseil records with "Signature par email" status
  to demonstrate the workflow and UI features.
*/

INSERT INTO devoirs_conseil (
  client_name,
  civilite,
  nom,
  prenom,
  telephone,
  email,
  adresse,
  ville,
  code_postal,
  date_naissance,
  statut_professionnel,
  profession,
  besoins,
  risques,
  budget,
  situation_familiale,
  situation_professionnelle,
  projets,
  autres_remarques,
  produits_proposes,
  garanties,
  exclusions,
  limites,
  conditions,
  contrat_choisi,
  options,
  montants_garantie,
  adequation_confirmee,
  risques_refus,
  signature_client,
  date_signature,
  status,
  signature_type,
  created_at,
  updated_at
) VALUES
(
  'Sophie Martin',
  'Mme',
  'Martin',
  'Sophie',
  '0612345678',
  'sophie.martin@email.com',
  '42 Avenue des Champs',
  'Paris',
  '75008',
  '1985-03-15',
  'Salariée',
  'Ingénieur IT',
  'Assurance retraite et prévoyance',
  'Couverture insuffisante',
  '300 €/mois',
  'Mariée, 2 enfants',
  'CDI - Secteur IT',
  'Préparation retraite',
  'Dossier en attente de signature du client',
  'PER, Assurance Vie, Prévoyance',
  'Couverture complète décès et invalidité',
  'Exclusions médicales standard',
  'Limites standard',
  'Conditions standard',
  'PER + Assurance Vie',
  'Options complémentaires',
  '500000 €',
  true,
  'Risque de précarité à la retraite',
  'S. Martin',
  '2025-01-10',
  'Signature par email',
  'email',
  now(),
  now()
),
(
  'Jean Dupont',
  'M.',
  'Dupont',
  'Jean',
  '0623456789',
  'jean.dupont@email.com',
  '15 Rue de la Paix',
  'Lyon',
  '69000',
  '1978-07-22',
  'Salarié',
  'Directeur Commercial',
  'Prévoyance professionnelle',
  'Couverture actuelle insuffisante',
  '450 €/mois',
  'Marié, 3 enfants',
  'CDI - Directeur',
  'Augmentation du capital-décès',
  'En attente de validation client',
  'Prévoyance, Santé, Retraite',
  'Indemnité décès 500k€',
  'Exclusions sport extrême',
  'Couverture jusqu''à 70 ans',
  'Conditions favorables',
  'Prévoyance Gold',
  'Options santé premium',
  '600000 €',
  true,
  'Couverture insuffisante actuellement',
  'J. Dupont',
  '2025-01-09',
  'Signature par email',
  'email',
  now(),
  now()
),
(
  'Marie Leclerc',
  'Mme',
  'Leclerc',
  'Marie',
  '0634567890',
  'marie.leclerc@email.com',
  '78 Boulevard Saint-Germain',
  'Bordeaux',
  '33000',
  '1990-11-08',
  'Indépendante',
  'Consultante',
  'Retraite et prévoyance',
  'Statut indépendant - couverture faible',
  '350 €/mois',
  'Célibataire',
  'Activité libérale depuis 5 ans',
  'Sécuriser sa retraite',
  'Dossier bien avancé',
  'PER, Assurance Vie, Prévoyance',
  'Couverture retraite renforcée',
  'Exclusions standard',
  'Couverture complète',
  'Conditions favorables indépendants',
  'PER Indépendants',
  'Options retraite progressive',
  '400000 €',
  true,
  'Insuffisance de couverture sociale',
  'M. Leclerc',
  '2025-01-11',
  'Signature par email',
  'email',
  now(),
  now()
),
(
  'Pierre Bernard',
  'M.',
  'Bernard',
  'Pierre',
  '0645678901',
  'pierre.bernard@email.com',
  '25 Rue de Rivoli',
  'Toulouse',
  '31000',
  '1972-05-30',
  'Salarié',
  'Manager Ressources Humaines',
  'Épargne retraite',
  'Préparer une retraite confortable',
  '400 €/mois',
  'Marié, 1 enfant',
  'CDI depuis 20 ans',
  'Retraite anticipée à 60 ans',
  'Client très intéressé',
  'PER, Assurance Vie',
  'Couverture épargne retraite',
  'Aucune',
  'Couverture jusqu''à 70 ans',
  'Conditions attractives',
  'PER Signature',
  'Versement initial 10k€',
  '300000 €',
  true,
  'Besoin de diversification',
  'P. Bernard',
  '2025-01-12',
  'Signature par email',
  'email',
  now(),
  now()
),
(
  'Claire Rousseau',
  'Mme',
  'Rousseau',
  'Claire',
  '0656789012',
  'claire.rousseau@email.com',
  '50 Avenue Montaigne',
  'Marseille',
  '13000',
  '1995-09-18',
  'Salariée',
  'Avocate',
  'Protection famille et retraite',
  'Famille nombreuse à protéger',
  '500 €/mois',
  'Mariée, 2 enfants',
  'Cabinet d''avocats - Associée',
  'Constituer un capital pour les enfants',
  'Signature prévue cette semaine',
  'Assurance Vie, Prévoyance, PER',
  'Couverture famille complète',
  'Exclusions juridiques',
  'Couverture 100% des besoins',
  'Conditions standard',
  'Assurance Vie Prestige',
  'Gestion pilotée',
  '750000 €',
  true,
  'Protection insuffisante',
  'C. Rousseau',
  '2025-01-13',
  'Signature par email',
  'email',
  now(),
  now()
);
