/*
  # Add Sample Devoirs de Conseil with Varied Statuses
  
  This migration creates sample data for testing with various signature statuses:
  - Non signé (unsigned)
  - Signature physique (physically signed)
  - Signature par email (email signature)
  - Envoyé en AF (sent to affaires nouvelles)
  
  ## Sample Data
  - Creates 10 sample devoirs de conseil
  - Different statuses for testing UI
  - Realistic client data
*/

-- Insert sample devoirs de conseil with varied statuses
INSERT INTO devoirs_conseil (
  client_name,
  besoins,
  risques,
  budget,
  situation_familiale,
  situation_professionnelle,
  projets,
  autres_remarques,
  produits_proposes,
  garanties,
  exclusions,
  limites,
  conditions,
  contrat_choisi,
  options,
  montants_garantie,
  adequation_confirmee,
  risques_refus,
  signature_client,
  date_signature,
  signature_status,
  signature_type,
  affaires_nouvelles_status,
  created_at
) VALUES
-- Non signés
(
  'Sophie Martin',
  'Protection financière famille',
  'Risques liés à l''activité professionnelle',
  '250€/mois',
  'Mariée, 2 enfants',
  'Cadre supérieur',
  'Acquisition résidence principale',
  'Besoin de conseil personnalisé',
  'PER - Assurance Vie',
  'Garanties décès et invalidité',
  'Exclusions sports extrêmes',
  'Limites standards',
  'Conditions générales applicables',
  'PER Individuel BNP Paribas',
  'Option gestion pilotée',
  '200 000€',
  false,
  '',
  '',
  '2024-03-15',
  'Non signé',
  NULL,
  'pending',
  '2024-03-15 10:00:00'
),
(
  'Thomas Dubois',
  'Épargne retraite',
  'Risques inflation',
  '400€/mois',
  'Célibataire',
  'Profession libérale',
  'Optimisation fiscale',
  'Loi Madelin',
  'PER',
  'Garanties standards',
  'Exclusions standards',
  'Limites contractuelles',
  'Conditions habituelles',
  'PER Madelin Generali',
  'Option sécurisée',
  '150 000€',
  false,
  '',
  '',
  '2024-03-16',
  'Non signé',
  NULL,
  'pending',
  '2024-03-16 11:30:00'
),
(
  'Émilie Rousseau',
  'Protection crédit immobilier',
  'Risques santé',
  '180€/mois',
  'Mariée, 1 enfant',
  'Pharmacienne',
  'Achat résidence principale',
  'Prêt en cours',
  'Assurance Emprunteur',
  'Garanties décès et PTIA',
  'Exclusions standards',
  'Limites âge 65 ans',
  'Conditions médicales',
  'Assurance Emprunteur Cardif',
  'Garanties essentielles',
  '250 000€',
  false,
  '',
  '',
  '2024-03-17',
  'Non signé',
  NULL,
  'pending',
  '2024-03-17 09:00:00'
),
-- Signés physiquement
(
  'Marie Leclerc',
  'Prévoyance familiale',
  'Risques santé',
  '180€/mois',
  'Mariée, 3 enfants',
  'Enseignante',
  'Protection famille',
  'Urgence familiale',
  'Prévoyance - Santé',
  'Garanties hospitalisation',
  'Exclusions maladies antérieures',
  'Délais de carence',
  'Conditions spécifiques',
  'Prévoyance AXA',
  'Garanties renforcées',
  '100 000€',
  true,
  '',
  'Marie Leclerc',
  '2024-03-10',
  'Signature physique',
  'immediate',
  'pending',
  '2024-03-10 14:20:00'
),
(
  'Jean Moreau',
  'Investissement immobilier',
  'Risques locatifs',
  '500€/mois',
  'Pacsé',
  'Entrepreneur',
  'Investissement locatif',
  'Défiscalisation',
  'Assurance Vie - SCPI',
  'Garanties capital',
  'Exclusions standards',
  'Limites fonds euros',
  'Conditions particulières',
  'Assurance Vie Allianz',
  'Diversification patrimoine',
  '300 000€',
  true,
  '',
  'Jean Moreau',
  '2024-03-12',
  'Signature physique',
  'immediate',
  'pending',
  '2024-03-12 16:45:00'
),
(
  'Claire Bernard',
  'Épargne enfants',
  'Risques éducation',
  '150€/mois',
  'Divorcée, 1 enfant',
  'Infirmière',
  'Études supérieures enfant',
  'Sécuriser avenir',
  'Assurance Vie',
  'Garanties décès',
  'Exclusions suicide',
  'Limites âge',
  'Conditions générales',
  'Assurance Vie Crédit Agricole',
  'Gestion libre',
  '80 000€',
  true,
  '',
  'Claire Bernard',
  '2024-03-14',
  'Signature physique',
  'immediate',
  'pending',
  '2024-03-14 09:15:00'
),
-- Signature par email
(
  'Pierre Rousseau',
  'Complément retraite',
  'Risques longévité',
  '350€/mois',
  'Marié, enfants majeurs',
  'Cadre dirigeant',
  'Préparer retraite',
  'Transmission patrimoine',
  'PER - Assurance Vie',
  'Garanties rente',
  'Exclusions standards',
  'Limites réglementaires',
  'Conditions classiques',
  'PER SwissLife',
  'Gestion équilibrée',
  '250 000€',
  true,
  '',
  'Pierre Rousseau',
  '2024-03-11',
  'Signature par email',
  'email',
  'pending',
  '2024-03-11 13:00:00'
),
(
  'Isabelle Petit',
  'Protection décès',
  'Risques familiale',
  '120€/mois',
  'Mariée, 2 enfants',
  'Fonctionnaire',
  'Sécuriser famille',
  'Prêt immobilier en cours',
  'Assurance Décès',
  'Garanties capital',
  'Exclusions sports',
  'Limites âge 70 ans',
  'Conditions médicales',
  'Décès CNP Assurances',
  'Option surprime',
  '200 000€',
  true,
  '',
  'Isabelle Petit',
  '2024-03-13',
  'Signature par email',
  'email',
  'pending',
  '2024-03-13 15:30:00'
),
-- Envoyés en AF
(
  'Laurent Garnier',
  'Optimisation fiscale',
  'Risques TMI',
  '600€/mois',
  'Marié',
  'Chef d''entreprise',
  'Réduction impôts',
  'Loi Madelin complète',
  'PER Madelin - Prévoyance',
  'Garanties complètes',
  'Exclusions standards',
  'Limites déductibilité',
  'Conditions Madelin',
  'PER Madelin MMA',
  'Package dirigeant',
  '400 000€',
  true,
  '',
  'Laurent Garnier',
  '2024-03-08',
  'Envoyé en AF',
  'immediate',
  'sent',
  '2024-03-08 10:30:00'
),
(
  'François Lambert',
  'Protection famille',
  'Risques incapacité',
  '220€/mois',
  'Marié, 1 enfant',
  'Artisan',
  'Sécurité professionnelle',
  'Activité risquée',
  'Prévoyance TNS',
  'Garanties ITT/IPT',
  'Exclusions profession',
  'Limites indemnisation',
  'Conditions TNS',
  'Prévoyance Malakoff Humanis',
  'Formule artisan',
  '150 000€',
  true,
  '',
  'François Lambert',
  '2024-03-07',
  'Envoyé en AF',
  'immediate',
  'sent',
  '2024-03-07 11:45:00'
)
ON CONFLICT (id) DO NOTHING;
